[2013-10-31 12:43:18] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:14] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:34] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:54] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:44:59] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:45:13] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:52:34] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:52:38] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:53:18] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:53:35] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:53:41] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:58:21] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 12:58:37] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:10:55] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:00] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:02] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:10] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:13] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:28] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:29] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:29] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:30:29] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 13:39:06] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 15:51:06] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 16:15:21] Exception.CRITICAL: Exception thrown: exception 'Exception' with message 'test' in D:\localroot\staticcms\System\Framework\Application.php:27
Stack trace:
#0 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#1 {main} [] []
[2013-10-31 16:16:14] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:16:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:16:46] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:17:00] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:17:24] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:17:28] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:23:59] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:06] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:11] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:20] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:26] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:31] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:35] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:24:56] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:25:39] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:25:42] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-10-31 16:25:47] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-03 14:01:43] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-03 18:23:47] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\staticcms\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\staticcms\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\staticcms\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 09:07:02] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:14:10] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:14:13] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:14:16] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:39:53] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:40:02] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:50:21] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scms.table_name' doesn't exist' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:52:57] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 18:53:00] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:58:40] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usernamed' in 'field list'' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:59:37] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 18:59:43] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scms.sdcms_users' doesn't exist' in D:\localroot\framework\Application\Model\User.php:46
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(46): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 20:46:51] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-04 20:46:56] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:57
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(57): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-04 21:28:40] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'testuser' for key 'username'' in D:\localroot\framework\Application\Model\User.php:75
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(75): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(23): Application\Model\User->update()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 09:08:33] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:19:31] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:21:23] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:21:27] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:36:24] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 09:36:30] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 10:15:09] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: parameter was not defined' in D:\localroot\framework\Application\Model\User.php:136
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(136): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:15:38] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: parameter was not defined' in D:\localroot\framework\Application\Model\User.php:138
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(138): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:16:53] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\localroot\framework\Application\Model\User.php:138
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(138): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:17:06] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\localroot\framework\Application\Model\User.php:140
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(140): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:17:23] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in D:\localroot\framework\Application\Model\User.php:140
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(140): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:18:23] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 'test'' at line 1' in D:\localroot\framework\Application\Model\User.php:140
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(140): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(20): Application\Model\User->exists(Array)
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:18:55] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'username'' in D:\localroot\framework\Application\Model\User.php:58
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(58): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(27): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 10:20:47] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'username'' in D:\localroot\framework\Application\Model\User.php:58
Stack trace:
#0 D:\localroot\framework\Application\Model\User.php(58): PDOStatement->execute(Array)
#1 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(27): Application\Model\User->create()
#2 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#3 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#4 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#5 {main} [] []
[2013-11-05 14:35:56] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'Parameter should be an array! Got: boolean' in D:\localroot\framework\System\Framework\Form\FormHandler.php:27
Stack trace:
#0 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(21): System\Framework\Form\FormHandler->getFields(true)
#1 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#3 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-05 20:38:19] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:38:19] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:38:57] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:27] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:33] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:36] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:41] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:46] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:39:55] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:40:00] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php:21
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php(21): PDO->__construct('mysql:dbname=sc...', 'root', '')
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Model.php(16): System\Framework\Database\Database->__construct()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Model/Auth.php(15): System\Framework\Model->getDatabase()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/LoginController.php(19): Application\Model\Auth->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\LoginController->index()
#5 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#6 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#7 {main} [] []
[2013-11-05 20:41:04] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'fail to load language file '/Applications/XAMPP/xamppfiles/htdocs/framework/System/lang/en.php'' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Form/FormValidator.php:61
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/RegisterController.php(23): System\Framework\Form\FormValidator->__construct(Array)
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-05 20:42:00] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:42:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:42:57] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:42:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:43:04] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:43:07] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:44:40] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:45:56] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:45:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:46:05] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:46:09] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:46:50] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php:73
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-05 20:47:55] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php:21
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php(21): PDO->__construct('mysql:dbname=sc...', 'root', '')
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Model.php(16): System\Framework\Database\Database->__construct()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Model/Auth.php(15): System\Framework\Model->getDatabase()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/LoginController.php(19): Application\Model\Auth->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\LoginController->index()
#5 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#6 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#7 {main} [] []
[2013-11-05 20:55:51] PDOException.CRITICAL: Exception thrown: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php:21
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Database/Database.php(21): PDO->__construct('mysql:dbname=sc...', 'root', '')
#1 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Model.php(16): System\Framework\Database\Database->__construct()
#2 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Model/Auth.php(15): System\Framework\Model->getDatabase()
#3 /Applications/XAMPP/xamppfiles/htdocs/framework/Application/Controller/Auth/LoginController.php(19): Application\Model\Auth->__construct()
#4 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/MainController.php(70): Application\Controller\Auth\LoginController->index()
#5 /Applications/XAMPP/xamppfiles/htdocs/framework/System/Framework/Application.php(27): System\Framework\Maincontroller->execute()
#6 /Applications/XAMPP/xamppfiles/htdocs/framework/web/index.php(31): System\Framework\Application->runApp()
#7 {main} [] []
[2013-11-06 13:40:32] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-06 13:40:54] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 09:39:52] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 09:39:55] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 09:40:02] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'fail to load language file 'D:\localroot\framework\System/lang/en.php'' in D:\localroot\framework\System\Framework\Form\FormValidator.php:61
Stack trace:
#0 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(24): System\Framework\Form\FormValidator->__construct(Array)
#1 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#3 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-07 09:43:05] InvalidArgumentException.CRITICAL: Exception thrown: exception 'InvalidArgumentException' with message 'Rule 'equal' has not been registered with System\Framework\Form\FormValidator::addRule().' in D:\localroot\framework\System\Framework\Form\FormValidator.php:535
Stack trace:
#0 D:\localroot\framework\Application\Controller\Auth\RegisterController.php(27): System\Framework\Form\FormValidator->rule('equal', 'password', Array)
#1 D:\localroot\framework\System\Framework\MainController.php(70): Application\Controller\Auth\RegisterController->index()
#2 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#3 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#4 {main} [] []
[2013-11-07 11:53:16] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:43:58] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:45:16] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:46:20] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 13:48:39] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:04:51] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:38] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:43] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:45] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
[2013-11-07 16:18:51] ErrorException.CRITICAL: Exception thrown: exception 'ErrorException' with message 'Page not found' in D:\localroot\framework\System\Framework\MainController.php:73
Stack trace:
#0 D:\localroot\framework\System\Framework\Application.php(27): System\Framework\Maincontroller->execute()
#1 D:\localroot\framework\web\index.php(31): System\Framework\Application->runApp()
#2 {main} [] []
